### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by yacchin1205** [NII-cloud-operation/Jupyter-LC_wrapper#8]
In python3...

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 578, in execute_request
    super(PythonKernelBuffered, self).execute_request(stream, ident, parent)
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 604, in do_execute
    timeout=None, output_hook=output_hook, stdin_hook=stdin_hook, reply_hook=reply_hook)
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 850, in execute_interactive
    return reply_hook(msg_id, timeout=timeout)
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 540, in reply_hook_summarize
    file_full_path = self.file_full_path.decode(getfilesystemencoding())
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by yacchin1205** [comment]
I assume that self.file_full_path is expected to be `str` (not `unicode`) type. However, string literal in Python3 is always treated as unicode string... and the error occurs.

@shingo78  Any ideas?

**Comment by shingo78** [comment]
In my idea, 
- In Python2, use `unicode` type filename instead of `str` type
- In Python3, use `str` type filename

However, file I/O functions in python2 may return `str` type object. (e.g. `os.getcwd()` returns `str` object)
So, if `str` object is returned it should be converted to unicode object.
For example:
```
def unicode_filename(filename):
    if sys.version_info[0] >= 3:
        return filename
    if isinstance(filename, str):
        return filename.decode(getfilesystemencoding())
    return filename
```

**Comment by yacchin1205** [comment]
@shingo78 Thanks. Alternatively... I've found that Python2 has `os.getcwdu` function which returns pathname in unicode.
(Dive into Python3 introduces it...: https://books.google.co.jp/books?id=hWpf9r9CrugC&pg=PA323&lpg=PA323&dq=python+2+os+getcwdu&source=bl&ots=NaLut4p-Uy&sig=fdZmy57PG3DCOjq9wrL6kkktJaE&hl=ja&sa=X&ved=0ahUKEwjz3Me4sI_UAhUMzbwKHRJZDLAQ6AEIQzAE#v=onepage&q=python%202%20os%20getcwdu&f=false )

Using this function, we can keep the all variables related to paths in unicode... I'm going to try to fix it.

```
try:
    # Python 2
    from os import getcwdu as getcwd
except:
    # Python 3
    from os import getcwd

# get path of current working directory in *correct* character encoding
p = getcwd()
print('value={}, type={}'.format(p, type(p)))
```

**Comment by shingo78** [comment]
@yacchin1205 Thanks. I couldn't find this. This is better.
